### ISSUE TITLE
SVG icon name issue? Grey icon for Airport from functional site sld

### ISSUE THREAD

**Issue by rjruss** [OrdnanceSurvey/OS-VectorMap-District-stylesheets#1]
Hi, 
First*\* thank you*\* for the SLDs for Geoserver, it is just what I wanted to try out.

When I do use them on my install of Geoserver then I get a big grey square for airports.
Checking the SLD definition in FunctionalSite_FullColour.sld I can see the following

```
            <OnlineResource xlink:href="ordnance_survey/AirTrans-fc.svg"/>
```

I can find only Airport-fc.svg in the ordnance_survey directory. So I swapped out the AirTrans-fc for Airport in the sld I use and now it does show an icon I want for the airport. Only found this out as I was interested in Birmingham airport and will be using more of the SLDs for other areas soon.

Thank you your work and providing these slds.

Best Regards,

Robert

**Comment by ghost** [comment]
Thanks Robert and good spot. This seems to be an error just with the functional site SLDs.
We will however be releasing a new set of SLDs in the next week for the new version of the product, I will ensure this error is corrected in those.
