### ISSUE TITLE
Geopackage Connection

### ISSUE THREAD

**Issue by SeanMcV** [OrdnanceSurvey/OS-VectorMap-District-stylesheets#3]
In ArcMap, I have added the .lyr file as described in the Readme, but when I try to connect to the geopackage datasource for any of the layers, the only available option is 'Change Query', rather than the usual 'Change Datasource'. I cannot see how to connect to the geopackage, even though I have added a link in ArcCatalog.

**Comment by egil1978** [comment]
The layer files have now been updated for both full colour and backdrop and should now allow you to update each layer against the relevant data within the VMD geopackage.
